// src/types/unified.ts
import type {
  Flight,
  GateEvent,
  Baggage,
  Passenger,
  SecurityScreening,
  MaintenanceLog,
  StaffShift,
  RetailTransaction,
  Alert,
  TerminalSummary,
  BaggageSummary,
  SecurityHeatmapEntry,
  StaffingGap,
  MaintenanceSummary,
  RetailSummary,
} from './airport';

/**
 * UnifiedFlight — The master type joining ALL datasets around a single flight.
 * This is the golden key: every chart, drilldown, and alert traces back here.
 */
export interface UnifiedFlight {
  // Base flight data
  flight: Flight;

  // Related records from other datasets
  gateEvents: GateEvent[];
  bags: Baggage[];
  passengers: Passenger[];
  maintenanceItems: MaintenanceLog[];
  securityCheckpoints: SecurityScreening[];
  retailTransactions: RetailTransaction[];

  // ===== Computed Fields =====
  /** Weighted risk score (0-100): 40% gate conflicts + 30% open maintenance + 30% historical delay */
  delayRiskScore: number;
  /** Percentage of bags with status 'Loaded' vs total bags */
  baggageReconciliationRate: number;
  /** Actual passengers / capacity * 100 */
  paxLoadFactor: number;
  /** Estimated turnaround time in minutes from gate events */
  estimatedTurnaroundMinutes: number;
  /** Staff coverage status based on active shifts for this flight's terminal */
  staffCoverageStatus: 'OK' | 'LOW' | 'CRITICAL';
  /** Turnaround status from gate timing comparison */
  turnaroundStatus: 'ON_TRACK' | 'AT_RISK' | 'DELAYED';
  /** Revenue generated by passengers on this flight */
  flightRevenue: number;
}

/**
 * DataStore — The raw parsed data from all 8 CSVs.
 * Returned by loadAllDatasets().
 */
export interface DataStore {
  flights: Flight[];
  gateEvents: GateEvent[];
  baggage: Baggage[];
  passengers: Passenger[];
  securityScreenings: SecurityScreening[];
  maintenanceLogs: MaintenanceLog[];
  staffShifts: StaffShift[];
  retailTransactions: RetailTransaction[];
  /** Timestamp of when data was loaded */
  loadedAt: Date;
}

/**
 * FlightIndex — Lookup map keyed by flight_id -> UnifiedFlight
 */
export type FlightIndex = Map<string, UnifiedFlight>;

/**
 * GateIndex — Lookup map keyed by gate_id -> GateEvent[]
 */
export type GateIndex = Map<string, GateEvent[]>;

/**
 * TimelineEntry — A single event in a flight's timeline
 */
export interface TimelineEntry {
  timestamp: Date;
  type: 'departure' | 'arrival' | 'gate' | 'baggage' | 'boarding' | 'maintenance' | 'security';
  label: string;
  details: string;
  flight_id: string;
}

/**
 * TimelineIndex — Lookup map keyed by flight_id -> sorted TimelineEntry[]
 */
export type TimelineIndex = Map<string, TimelineEntry[]>;

/**
 * DerivedOpsData — Pre-computed analytics for the entire dataset.
 * Created by computeDerivedOpsData() in derivedOpsData.ts.
 */
export interface DerivedOpsData {
  activeAlerts: Alert[];
  terminalSummaries: TerminalSummary[];
  topDelayedAirlines: { airline: string; avgDelay: number; flightCount: number }[];
  baggageSummary: BaggageSummary;
  securityHeatmap: SecurityHeatmapEntry[];
  staffingGaps: StaffingGap[];
  maintenanceSummary: MaintenanceSummary;
  retailSummary: RetailSummary;
  // Quick-access stats
  totalFlights: number;
  totalPassengers: number;
  overallOnTimeRate: number;
  avgDelayMinutes: number;
}

/**
 * AirportContextValue — Provided by React Context to all components
 */
export interface AirportContextValue {
  store: DataStore | null;
  flightIndex: FlightIndex;
  gateIndex: GateIndex;
  timelineIndex: TimelineIndex;
  derivedData: DerivedOpsData | null;
  isLoading: boolean;
  error: string | null;
}
